// NSE Stock Symbols for Pattern Scanner
// 799 unique NSE-listed stocks with Yahoo Finance .NS suffix
// Organized by sector for easy reference

const NSE_SYMBOLS = [

  // ========================================
  // === ENERGY ===
  // ========================================
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'ONGC.NS', name: 'Oil and Natural Gas Corporation', sector: 'Energy' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum', sector: 'Energy' },
  { symbol: 'HINDPETRO.NS', name: 'Hindustan Petroleum', sector: 'Energy' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corporation', sector: 'Energy' },
  { symbol: 'GAIL.NS', name: 'GAIL India', sector: 'Energy' },
  { symbol: 'OIL.NS', name: 'Oil India', sector: 'Energy' },
  { symbol: 'PETRONET.NS', name: 'Petronet LNG', sector: 'Energy' },
  { symbol: 'MGL.NS', name: 'Mahanagar Gas', sector: 'Energy' },
  { symbol: 'IGL.NS', name: 'Indraprastha Gas', sector: 'Energy' },
  { symbol: 'GUJGASLTD.NS', name: 'Gujarat Gas', sector: 'Energy' },
  { symbol: 'CASTROLIND.NS', name: 'Castrol India', sector: 'Energy' },
  { symbol: 'MRPL.NS', name: 'Mangalore Refinery and Petrochemicals', sector: 'Energy' },
  { symbol: 'CHENNPETRO.NS', name: 'Chennai Petroleum', sector: 'Energy' },
  { symbol: 'GSPL.NS', name: 'Gujarat State Petronet', sector: 'Energy' },
  { symbol: 'AEGISCHEM.NS', name: 'Aegis Logistics', sector: 'Energy' },
  { symbol: 'ATGL.NS', name: 'Adani Total Gas', sector: 'Energy' },
  { symbol: 'GULFOILLUB.NS', name: 'Gulf Oil Lubricants India', sector: 'Energy' },
  { symbol: 'TIDEWATER.NS', name: 'Tide Water Oil', sector: 'Energy' },
  { symbol: 'HINDOILEXP.NS', name: 'Hindustan Oil Exploration', sector: 'Energy' },
  { symbol: 'SELAN.NS', name: 'Selan Exploration Technology', sector: 'Energy' },
  { symbol: 'CONFIPET.NS', name: 'Confidence Petroleum', sector: 'Energy' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy', sector: 'Energy' },

  // ========================================
  // === IT ===
  // ========================================
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'INFY.NS', name: 'Infosys', sector: 'IT' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'WIPRO.NS', name: 'Wipro', sector: 'IT' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree', sector: 'IT' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis', sector: 'IT' },
  { symbol: 'COFORGE.NS', name: 'Coforge Limited', sector: 'IT' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems', sector: 'IT' },
  { symbol: 'LTTS.NS', name: 'L and T Technology Services', sector: 'IT' },
  { symbol: 'OFSS.NS', name: 'Oracle Financial Services', sector: 'IT' },
  { symbol: 'CYIENT.NS', name: 'Cyient Limited', sector: 'IT' },
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies', sector: 'IT' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', sector: 'IT' },
  { symbol: 'BIRLASOFT.NS', name: 'Birlasoft Limited', sector: 'IT' },
  { symbol: 'ZENSAR.NS', name: 'Zensar Technologies', sector: 'IT' },
  { symbol: 'MASTEK.NS', name: 'Mastek Limited', sector: 'IT' },
  { symbol: 'ROUTE.NS', name: 'Route Mobile', sector: 'IT' },
  { symbol: 'TANLA.NS', name: 'Tanla Platforms', sector: 'IT' },
  { symbol: 'SONATSOFTW.NS', name: 'Sonata Software', sector: 'IT' },
  { symbol: 'NIITLTD.NS', name: 'NIIT Limited', sector: 'IT' },
  { symbol: 'NEWGEN.NS', name: 'Newgen Software Technologies', sector: 'IT' },
  { symbol: 'INTELLECT.NS', name: 'Intellect Design Arena', sector: 'IT' },
  { symbol: 'DATAPATTNS.NS', name: 'Data Patterns India', sector: 'IT' },
  { symbol: 'RATEGAIN.NS', name: 'RateGain Travel Technologies', sector: 'IT' },
  { symbol: 'LATENTVIEW.NS', name: 'Latent View Analytics', sector: 'IT' },
  { symbol: 'AFFLE.NS', name: 'Affle India', sector: 'IT' },
  { symbol: 'ECLERX.NS', name: 'eClerx Services', sector: 'IT' },
  { symbol: 'QUICKHEAL.NS', name: 'Quick Heal Technologies', sector: 'IT' },
  { symbol: 'NUCLEUS.NS', name: 'Nucleus Software Exports', sector: 'IT' },
  { symbol: 'POLICYBZR.NS', name: 'PB Fintech (PolicyBazaar)', sector: 'IT' },
  { symbol: 'NYKAA.NS', name: 'FSN E-Commerce (Nykaa)', sector: 'IT' },
  { symbol: 'PAYTM.NS', name: 'One 97 Communications (Paytm)', sector: 'IT' },
  { symbol: 'CARTRADE.NS', name: 'CarTrade Tech', sector: 'IT' },
  { symbol: 'MAPMYINDIA.NS', name: 'CE Info Systems (MapmyIndia)', sector: 'IT' },
  { symbol: 'ZOMATO.NS', name: 'Zomato Limited', sector: 'IT' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge India', sector: 'IT' },
  { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds Technologies', sector: 'IT' },
  { symbol: 'JUSTDIAL.NS', name: 'Just Dial', sector: 'IT' },
  { symbol: 'INDIAMART.NS', name: 'IndiaMART InterMESH', sector: 'IT' },
  { symbol: 'TATATECH.NS', name: 'Tata Technologies', sector: 'IT' },
  { symbol: 'SASKEN.NS', name: 'Sasken Technologies', sector: 'IT' },
  { symbol: 'RSYSTEMS.NS', name: 'R Systems International', sector: 'IT' },
  { symbol: 'EMUDHRA.NS', name: 'eMudhra Limited', sector: 'IT' },
  { symbol: 'NETWEB.NS', name: 'Netweb Technologies India', sector: 'IT' },
  { symbol: 'FIRSTSOUR.NS', name: 'Firstsource Solutions', sector: 'IT' },
  { symbol: 'AXISCADES.NS', name: 'AXISCADES Technologies', sector: 'IT' },
  { symbol: 'CMSINFO.NS', name: 'CMS Info Systems', sector: 'IT' },
  { symbol: 'DATAMATICS.NS', name: 'Datamatics Global Services', sector: 'IT' },
  { symbol: 'BLS.NS', name: 'BLS International Services', sector: 'IT' },
  { symbol: 'EXPLEOSOL.NS', name: 'Expleo Solutions', sector: 'IT' },
  { symbol: 'SAKSOFT.NS', name: 'Saksoft Limited', sector: 'IT' },
  { symbol: 'RAMCOSYS.NS', name: 'Ramco Systems', sector: 'IT' },
  { symbol: 'VAKRANGEE.NS', name: 'Vakrangee', sector: 'IT' },
  { symbol: 'ONMOBILE.NS', name: 'OnMobile Global', sector: 'IT' },
  { symbol: 'REDINGTON.NS', name: 'Redington Limited', sector: 'IT' },
  { symbol: 'ACCELYA.NS', name: 'Accelya Solutions India', sector: 'IT' },
  { symbol: 'BBOX.NS', name: 'Black Box', sector: 'IT' },
  { symbol: 'CYIENTDLM.NS', name: 'Cyient DLM', sector: 'IT' },
  { symbol: 'KSOLVES.NS', name: 'Ksolves India', sector: 'IT' },
  { symbol: '63MOONS.NS', name: '63 Moons Technologies', sector: 'IT' },

  // ========================================
  // === BANKING ===
  // ========================================
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', sector: 'Banking' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda', sector: 'Banking' },
  { symbol: 'CANBK.NS', name: 'Canara Bank', sector: 'Banking' },
  { symbol: 'PNB.NS', name: 'Punjab National Bank', sector: 'Banking' },
  { symbol: 'UNIONBANK.NS', name: 'Union Bank of India', sector: 'Banking' },
  { symbol: 'YESBANK.NS', name: 'Yes Bank', sector: 'Banking' },
  { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank', sector: 'Banking' },
  { symbol: 'BANDHANBNK.NS', name: 'Bandhan Bank', sector: 'Banking' },
  { symbol: 'CUB.NS', name: 'City Union Bank', sector: 'Banking' },
  { symbol: 'FEDERALBNK.NS', name: 'Federal Bank', sector: 'Banking' },
  { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank', sector: 'Banking' },
  { symbol: 'INDIANB.NS', name: 'Indian Bank', sector: 'Banking' },
  { symbol: 'IOB.NS', name: 'Indian Overseas Bank', sector: 'Banking' },
  { symbol: 'KARURVYSYA.NS', name: 'Karur Vysya Bank', sector: 'Banking' },
  { symbol: 'RBLBANK.NS', name: 'RBL Bank', sector: 'Banking' },
  { symbol: 'SOUTHBANK.NS', name: 'South Indian Bank', sector: 'Banking' },
  { symbol: 'CENTRALBK.NS', name: 'Central Bank of India', sector: 'Banking' },
  { symbol: 'BANKINDIA.NS', name: 'Bank of India', sector: 'Banking' },
  { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra', sector: 'Banking' },
  { symbol: 'UCOBANK.NS', name: 'UCO Bank', sector: 'Banking' },
  { symbol: 'PSB.NS', name: 'Punjab and Sind Bank', sector: 'Banking' },
  { symbol: 'IDBI.NS', name: 'IDBI Bank', sector: 'Banking' },
  { symbol: 'DCBBANK.NS', name: 'DCB Bank', sector: 'Banking' },
  { symbol: 'TMB.NS', name: 'Tamilnad Mercantile Bank', sector: 'Banking' },
  { symbol: 'EQUITASBNK.NS', name: 'Equitas Small Finance Bank', sector: 'Banking' },
  { symbol: 'UJJIVANSFB.NS', name: 'Ujjivan Small Finance Bank', sector: 'Banking' },
  { symbol: 'CSBBANK.NS', name: 'CSB Bank', sector: 'Banking' },
  { symbol: 'KTKBANK.NS', name: 'Karnataka Bank', sector: 'Banking' },
  { symbol: 'DHANLAXMI.NS', name: 'Dhanlaxmi Bank', sector: 'Banking' },
  { symbol: 'SURYODAY.NS', name: 'Suryoday Small Finance Bank', sector: 'Banking' },
  { symbol: 'ESAFSFB.NS', name: 'ESAF Small Finance Bank', sector: 'Banking' },
  { symbol: 'UTKARSHBNK.NS', name: 'Utkarsh Small Finance Bank', sector: 'Banking' },
  { symbol: 'FINOPB.NS', name: 'Fino Payments Bank', sector: 'Banking' },
  { symbol: 'JSFB.NS', name: 'Jana Small Finance Bank', sector: 'Banking' },

  // ========================================
  // === FINANCIAL SERVICES ===
  // ========================================
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', sector: 'Financial Services' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', sector: 'Financial Services' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance', sector: 'Financial Services' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', sector: 'Financial Services' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Investment', sector: 'Financial Services' },
  { symbol: 'ICICIGI.NS', name: 'ICICI Lombard General Insurance', sector: 'Financial Services' },
  { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life Insurance', sector: 'Financial Services' },
  { symbol: 'LICI.NS', name: 'Life Insurance Corporation', sector: 'Financial Services' },
  { symbol: 'PEL.NS', name: 'Piramal Enterprises', sector: 'Financial Services' },
  { symbol: 'RECLTD.NS', name: 'REC Limited', sector: 'Financial Services' },
  { symbol: 'SBICARD.NS', name: 'SBI Cards and Payment Services', sector: 'Financial Services' },
  { symbol: 'PFC.NS', name: 'Power Finance Corporation', sector: 'Financial Services' },
  { symbol: 'JIOFIN.NS', name: 'Jio Financial Services', sector: 'Financial Services' },
  { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance', sector: 'Financial Services' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', sector: 'Financial Services' },
  { symbol: 'MANAPPURAM.NS', name: 'Manappuram Finance', sector: 'Financial Services' },
  { symbol: 'BAJAJHLDNG.NS', name: 'Bajaj Holdings and Investment', sector: 'Financial Services' },
  { symbol: 'LICHSGFIN.NS', name: 'LIC Housing Finance', sector: 'Financial Services' },
  { symbol: 'CANFINHOME.NS', name: 'Can Fin Homes', sector: 'Financial Services' },
  { symbol: 'AAVAS.NS', name: 'Aavas Financiers', sector: 'Financial Services' },
  { symbol: 'ABCAPITAL.NS', name: 'Aditya Birla Capital', sector: 'Financial Services' },
  { symbol: 'ANGELONE.NS', name: 'Angel One', sector: 'Financial Services' },
  { symbol: 'CDSL.NS', name: 'Central Depository Services', sector: 'Financial Services' },
  { symbol: 'CRISIL.NS', name: 'CRISIL Limited', sector: 'Financial Services' },
  { symbol: 'HDFCAMC.NS', name: 'HDFC Asset Management', sector: 'Financial Services' },
  { symbol: 'IIFL.NS', name: 'IIFL Finance', sector: 'Financial Services' },
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance Corporation', sector: 'Financial Services' },
  { symbol: 'MFSL.NS', name: 'Max Financial Services', sector: 'Financial Services' },
  { symbol: 'MOTILALOFS.NS', name: 'Motilal Oswal Financial Services', sector: 'Financial Services' },
  { symbol: 'NAM-INDIA.NS', name: 'Nippon Life India AMC', sector: 'Financial Services' },
  { symbol: 'POONAWALLA.NS', name: 'Poonawalla Fincorp', sector: 'Financial Services' },
  { symbol: 'SUNDARMFIN.NS', name: 'Sundaram Finance', sector: 'Financial Services' },
  { symbol: 'UTIAMC.NS', name: 'UTI Asset Management', sector: 'Financial Services' },
  { symbol: 'CREDITACC.NS', name: 'CreditAccess Grameen', sector: 'Financial Services' },
  { symbol: 'HOMEFIRST.NS', name: 'Home First Finance', sector: 'Financial Services' },
  { symbol: 'FIVESTAR.NS', name: 'Five Star Business Finance', sector: 'Financial Services' },
  { symbol: 'FUSION.NS', name: 'Fusion Micro Finance', sector: 'Financial Services' },
  { symbol: 'NIACL.NS', name: 'New India Assurance', sector: 'Financial Services' },
  { symbol: 'GICRE.NS', name: 'General Insurance Corporation', sector: 'Financial Services' },
  { symbol: 'STARHEALTH.NS', name: 'Star Health Insurance', sector: 'Financial Services' },
  { symbol: 'BSE.NS', name: 'BSE Limited', sector: 'Financial Services' },
  { symbol: 'HUDCO.NS', name: 'Housing and Urban Development Corp', sector: 'Financial Services' },
  { symbol: 'TATAINVEST.NS', name: 'Tata Investment Corporation', sector: 'Financial Services' },
  { symbol: 'EDELWEISS.NS', name: 'Edelweiss Financial Services', sector: 'Financial Services' },
  { symbol: 'JMFINANCIL.NS', name: 'JM Financial', sector: 'Financial Services' },
  { symbol: 'ISEC.NS', name: 'ICICI Securities', sector: 'Financial Services' },
  { symbol: 'KFINTECH.NS', name: 'KFin Technologies', sector: 'Financial Services' },
  { symbol: 'ABSLAMC.NS', name: 'Aditya Birla Sun Life AMC', sector: 'Financial Services' },
  { symbol: 'MMFIN.NS', name: 'Mahindra and Mahindra Financial', sector: 'Financial Services' },
  { symbol: 'REPCOHOME.NS', name: 'Repco Home Finance', sector: 'Financial Services' },
  { symbol: 'SATIN.NS', name: 'Satin Creditcare Network', sector: 'Financial Services' },
  { symbol: 'SBFC.NS', name: 'SBFC Finance', sector: 'Financial Services' },
  { symbol: 'UGROCAP.NS', name: 'Ugro Capital', sector: 'Financial Services' },
  { symbol: 'APTUS.NS', name: 'Aptus Value Housing Finance', sector: 'Financial Services' },
  { symbol: 'CGCL.NS', name: 'Capri Global Capital', sector: 'Financial Services' },
  { symbol: 'ANANDRATHI.NS', name: 'Anand Rathi Wealth', sector: 'Financial Services' },
  { symbol: '5PAISA.NS', name: '5paisa Capital', sector: 'Financial Services' },
  { symbol: 'CHOICEIN.NS', name: 'Choice International', sector: 'Financial Services' },
  { symbol: 'INDOSTAR.NS', name: 'IndoStar Capital Finance', sector: 'Financial Services' },
  { symbol: 'PAISALO.NS', name: 'Paisalo Digital', sector: 'Financial Services' },
  { symbol: 'EMKAY.NS', name: 'Emkay Global Financial', sector: 'Financial Services' },

  // ========================================
  // === FMCG ===
  // ========================================
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'ITC.NS', name: 'ITC Limited', sector: 'FMCG' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India', sector: 'FMCG' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products', sector: 'FMCG' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries', sector: 'FMCG' },
  { symbol: 'DABUR.NS', name: 'Dabur India', sector: 'FMCG' },
  { symbol: 'MARICO.NS', name: 'Marico Limited', sector: 'FMCG' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer Products', sector: 'FMCG' },
  { symbol: 'COLPAL.NS', name: 'Colgate Palmolive India', sector: 'FMCG' },
  { symbol: 'EMAMILTD.NS', name: 'Emami Limited', sector: 'FMCG' },
  { symbol: 'JYOTHYLAB.NS', name: 'Jyothy Labs', sector: 'FMCG' },
  { symbol: 'RADICO.NS', name: 'Radico Khaitan', sector: 'FMCG' },
  { symbol: 'MCDOWELL-N.NS', name: 'United Spirits', sector: 'FMCG' },
  { symbol: 'VBL.NS', name: 'Varun Beverages', sector: 'FMCG' },
  { symbol: 'PGHH.NS', name: 'Procter and Gamble Hygiene', sector: 'FMCG' },
  { symbol: 'GILLETTE.NS', name: 'Gillette India', sector: 'FMCG' },
  { symbol: 'EIDPARRY.NS', name: 'EID Parry India', sector: 'FMCG' },
  { symbol: 'BIKAJI.NS', name: 'Bikaji Foods International', sector: 'FMCG' },
  { symbol: 'GODFRYPHLP.NS', name: 'Godfrey Phillips India', sector: 'FMCG' },
  { symbol: 'HATSUN.NS', name: 'Hatsun Agro Product', sector: 'FMCG' },
  { symbol: 'ZYDUSWELL.NS', name: 'Zydus Wellness', sector: 'FMCG' },
  { symbol: 'CCL.NS', name: 'CCL Products India', sector: 'FMCG' },
  { symbol: 'KRBL.NS', name: 'KRBL Limited', sector: 'FMCG' },
  { symbol: 'DEVYANI.NS', name: 'Devyani International', sector: 'FMCG' },
  { symbol: 'SAPPHIRE.NS', name: 'Sapphire Foods India', sector: 'FMCG' },
  { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks', sector: 'FMCG' },
  { symbol: 'WESTLIFE.NS', name: 'Westlife Foodworld', sector: 'FMCG' },
  { symbol: 'DODLA.NS', name: 'Dodla Dairy', sector: 'FMCG' },
  { symbol: 'HERITGFOOD.NS', name: 'Heritage Foods', sector: 'FMCG' },
  { symbol: 'PARAG.NS', name: 'Parag Milk Foods', sector: 'FMCG' },
  { symbol: 'BAJAJCON.NS', name: 'Bajaj Consumer Care', sector: 'FMCG' },
  { symbol: 'VSTIND.NS', name: 'VST Industries', sector: 'FMCG' },
  { symbol: 'PRATAAP.NS', name: 'Prataap Snacks', sector: 'FMCG' },
  { symbol: 'AWL.NS', name: 'Adani Wilmar', sector: 'FMCG' },
  { symbol: 'LTFOODS.NS', name: 'LT Foods', sector: 'FMCG' },
  { symbol: 'GLOBUSSPR.NS', name: 'Globus Spirits', sector: 'FMCG' },
  { symbol: 'GAEL.NS', name: 'Gujarat Ambuja Exports', sector: 'FMCG' },
  { symbol: 'BECTORFOOD.NS', name: 'Mrs Bectors Food Specialities', sector: 'FMCG' },
  { symbol: 'ADFFOODS.NS', name: 'ADF Foods', sector: 'FMCG' },
  { symbol: 'AMRUTANJAN.NS', name: 'Amrutanjan Health Care', sector: 'FMCG' },
  { symbol: 'ATFL.NS', name: 'Agro Tech Foods', sector: 'FMCG' },
  { symbol: 'ROSSELLIND.NS', name: 'Rossell India', sector: 'FMCG' },
  { symbol: 'RBA.NS', name: 'Restaurant Brands Asia', sector: 'FMCG' },
  { symbol: 'GODREJIND.NS', name: 'Godrej Industries', sector: 'FMCG' },

  // ========================================
  // === PHARMA ===
  // ========================================
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical', sector: 'Pharma' },
  { symbol: 'DRREDDY.NS', name: 'Dr Reddys Laboratories', sector: 'Pharma' },
  { symbol: 'CIPLA.NS', name: 'Cipla', sector: 'Pharma' },
  { symbol: 'DIVISLAB.NS', name: 'Divis Laboratories', sector: 'Pharma' },
  { symbol: 'BIOCON.NS', name: 'Biocon Limited', sector: 'Pharma' },
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories', sector: 'Pharma' },
  { symbol: 'LUPIN.NS', name: 'Lupin Limited', sector: 'Pharma' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma', sector: 'Pharma' },
  { symbol: 'ZYDUSLIFE.NS', name: 'Zydus Lifesciences', sector: 'Pharma' },
  { symbol: 'IPCALAB.NS', name: 'IPCA Laboratories', sector: 'Pharma' },
  { symbol: 'LAURUSLABS.NS', name: 'Laurus Labs', sector: 'Pharma' },
  { symbol: 'ABBOTINDIA.NS', name: 'Abbott India', sector: 'Pharma' },
  { symbol: 'GLAXO.NS', name: 'GlaxoSmithKline Pharma', sector: 'Pharma' },
  { symbol: 'PFIZER.NS', name: 'Pfizer India', sector: 'Pharma' },
  { symbol: 'SANOFI.NS', name: 'Sanofi India', sector: 'Pharma' },
  { symbol: 'GLENMARK.NS', name: 'Glenmark Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'AJANTPHARM.NS', name: 'Ajanta Pharma', sector: 'Pharma' },
  { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma', sector: 'Pharma' },
  { symbol: 'GRANULES.NS', name: 'Granules India', sector: 'Pharma' },
  { symbol: 'ASTRAZEN.NS', name: 'AstraZeneca Pharma India', sector: 'Pharma' },
  { symbol: 'ERIS.NS', name: 'Eris Lifesciences', sector: 'Pharma' },
  { symbol: 'STAR.NS', name: 'Strides Pharma Science', sector: 'Pharma' },
  { symbol: 'SOLARA.NS', name: 'Solara Active Pharma Sciences', sector: 'Pharma' },
  { symbol: 'IOLCP.NS', name: 'IOL Chemicals and Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'JBCHEPHARM.NS', name: 'JB Chemicals and Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'SUVENPHAR.NS', name: 'Suven Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'GLAND.NS', name: 'Gland Pharma', sector: 'Pharma' },
  { symbol: 'MANKIND.NS', name: 'Mankind Pharma', sector: 'Pharma' },
  { symbol: 'SYNGENE.NS', name: 'Syngene International', sector: 'Pharma' },
  { symbol: 'APLLTD.NS', name: 'Alembic Pharmaceuticals', sector: 'Pharma' },
  { symbol: 'WOCKPHARMA.NS', name: 'Wockhardt', sector: 'Pharma' },
  { symbol: 'CAPLIPOINT.NS', name: 'Caplin Point Laboratories', sector: 'Pharma' },
  { symbol: 'MARKSANS.NS', name: 'Marksans Pharma', sector: 'Pharma' },
  { symbol: 'SPARC.NS', name: 'Sun Pharma Advanced Research', sector: 'Pharma' },
  { symbol: 'BLISSGVS.NS', name: 'Bliss GVS Pharma', sector: 'Pharma' },
  { symbol: 'INDOCO.NS', name: 'Indoco Remedies', sector: 'Pharma' },
  { symbol: 'SHILPAMED.NS', name: 'Shilpa Medicare', sector: 'Pharma' },
  { symbol: 'FDC.NS', name: 'FDC Limited', sector: 'Pharma' },
  { symbol: 'WINDLAS.NS', name: 'Windlas Biotech', sector: 'Pharma' },
  { symbol: 'CONCORD.NS', name: 'Concord Biotech', sector: 'Pharma' },
  { symbol: 'SUPRIYA.NS', name: 'Supriya Lifescience', sector: 'Pharma' },
  { symbol: 'GLS.NS', name: 'Glenmark Life Sciences', sector: 'Pharma' },
  { symbol: 'PPLPHARMA.NS', name: 'Piramal Pharma', sector: 'Pharma' },
  { symbol: 'JUBILANT.NS', name: 'Jubilant Pharmova', sector: 'Pharma' },
  { symbol: 'MOREPENLAB.NS', name: 'Morepen Laboratories', sector: 'Pharma' },
  { symbol: 'ALEMBICLTD.NS', name: 'Alembic Limited', sector: 'Pharma' },
  { symbol: 'BLUEJET.NS', name: 'Blue Jet Healthcare', sector: 'Pharma' },
  { symbol: 'GUFICBIO.NS', name: 'Gufic Biosciences', sector: 'Pharma' },
  { symbol: 'RPEL.NS', name: 'RPG Life Sciences', sector: 'Pharma' },
  { symbol: 'THEMISMED.NS', name: 'Themis Medicare', sector: 'Pharma' },
  { symbol: 'NGLFINE.NS', name: 'NGL Fine-Chem', sector: 'Pharma' },
  { symbol: 'PANACEABIO.NS', name: 'Panacea Biotec', sector: 'Pharma' },
  { symbol: 'ADVENZYMES.NS', name: 'Advanced Enzyme Technologies', sector: 'Pharma' },
  { symbol: 'DCAL.NS', name: 'Dishman Carbogen Amcis', sector: 'Pharma' },
  { symbol: 'SEQUENT.NS', name: 'Sequent Scientific', sector: 'Pharma' },

  // ========================================
  // === HEALTHCARE ===
  // ========================================
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'LALPATHLAB.NS', name: 'Dr Lal PathLabs', sector: 'Healthcare' },
  { symbol: 'METROPOLIS.NS', name: 'Metropolis Healthcare', sector: 'Healthcare' },
  { symbol: 'FORTIS.NS', name: 'Fortis Healthcare', sector: 'Healthcare' },
  { symbol: 'MEDANTA.NS', name: 'Global Health (Medanta)', sector: 'Healthcare' },
  { symbol: 'KIMS.NS', name: 'Krishna Institute of Medical Sciences', sector: 'Healthcare' },
  { symbol: 'RAINBOW.NS', name: 'Rainbow Childrens Medicare', sector: 'Healthcare' },
  { symbol: 'NH.NS', name: 'Narayana Hrudayalaya', sector: 'Healthcare' },
  { symbol: 'MAXHEALTH.NS', name: 'Max Healthcare Institute', sector: 'Healthcare' },
  { symbol: 'VIJAYA.NS', name: 'Vijaya Diagnostic Centre', sector: 'Healthcare' },
  { symbol: 'POLYMED.NS', name: 'Poly Medicure', sector: 'Healthcare' },
  { symbol: 'MEDPLUS.NS', name: 'MedPlus Health Services', sector: 'Healthcare' },
  { symbol: 'ASTERDM.NS', name: 'Aster DM Healthcare', sector: 'Healthcare' },
  { symbol: 'HCG.NS', name: 'Healthcare Global Enterprises', sector: 'Healthcare' },
  { symbol: 'THYROCARE.NS', name: 'Thyrocare Technologies', sector: 'Healthcare' },
  { symbol: 'TARSONS.NS', name: 'Tarsons Products', sector: 'Healthcare' },

  // ========================================
  // === AUTO ===
  // ========================================
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki India', sector: 'Auto' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'M&M.NS', name: 'Mahindra and Mahindra', sector: 'Auto' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto', sector: 'Auto' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'TVSMOTOR.NS', name: 'TVS Motor Company', sector: 'Auto' },
  { symbol: 'ASHOKLEY.NS', name: 'Ashok Leyland', sector: 'Auto' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries', sector: 'Auto' },
  { symbol: 'BHARATFORG.NS', name: 'Bharat Forge', sector: 'Auto' },
  { symbol: 'EXIDEIND.NS', name: 'Exide Industries', sector: 'Auto' },
  { symbol: 'AMARAJABAT.NS', name: 'Amara Raja Energy', sector: 'Auto' },
  { symbol: 'MRF.NS', name: 'MRF Limited', sector: 'Auto' },
  { symbol: 'APOLLOTYRE.NS', name: 'Apollo Tyres', sector: 'Auto' },
  { symbol: 'CEATLTD.NS', name: 'CEAT Limited', sector: 'Auto' },
  { symbol: 'JKTYRE.NS', name: 'JK Tyre and Industries', sector: 'Auto' },
  { symbol: 'SUNDRMFAST.NS', name: 'Sundram Fasteners', sector: 'Auto' },
  { symbol: 'ENDURANCE.NS', name: 'Endurance Technologies', sector: 'Auto' },
  { symbol: 'MINDA.NS', name: 'Uno Minda', sector: 'Auto' },
  { symbol: 'SONACOMS.NS', name: 'Sona BLW Precision Forgings', sector: 'Auto' },
  { symbol: 'SCHAEFFLER.NS', name: 'Schaeffler India', sector: 'Auto' },
  { symbol: 'TIINDIA.NS', name: 'Tube Investments of India', sector: 'Auto' },
  { symbol: 'CRAFTSMAN.NS', name: 'Craftsman Automation', sector: 'Auto' },
  { symbol: 'GABRIEL.NS', name: 'Gabriel India', sector: 'Auto' },
  { symbol: 'GNA.NS', name: 'GNA Axles', sector: 'Auto' },
  { symbol: 'LUMAXTECH.NS', name: 'Lumax Auto Technologies', sector: 'Auto' },
  { symbol: 'SUBROS.NS', name: 'Subros Limited', sector: 'Auto' },
  { symbol: 'SUPRAJIT.NS', name: 'Suprajit Engineering', sector: 'Auto' },
  { symbol: 'FORCEMOT.NS', name: 'Force Motors', sector: 'Auto' },
  { symbol: 'ESCORTS.NS', name: 'Escorts Kubota', sector: 'Auto' },
  { symbol: 'OLECTRA.NS', name: 'Olectra Greentech', sector: 'Auto' },
  { symbol: 'JBMA.NS', name: 'JBM Auto', sector: 'Auto' },
  { symbol: 'SWARAJENG.NS', name: 'Swaraj Engines', sector: 'Auto' },
  { symbol: 'JAMNAUTO.NS', name: 'Jamna Auto Industries', sector: 'Auto' },
  { symbol: 'JTEKTINDIA.NS', name: 'JTEKT India', sector: 'Auto' },
  { symbol: 'HAPPYFORGE.NS', name: 'Happy Forgings', sector: 'Auto' },
  { symbol: 'MOTHERSON.NS', name: 'Samvardhana Motherson', sector: 'Auto' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch Limited', sector: 'Auto' },
  { symbol: 'GOODYEAR.NS', name: 'Goodyear India', sector: 'Auto' },
  { symbol: 'IGARASHI.NS', name: 'Igarashi Motors India', sector: 'Auto' },
  { symbol: 'ASAHIINDIA.NS', name: 'Asahi India Glass', sector: 'Auto' },
  { symbol: 'GREAVESCOT.NS', name: 'Greaves Cotton', sector: 'Auto' },
  { symbol: 'MAHSCOOTER.NS', name: 'Maharashtra Scooters', sector: 'Auto' },
  { symbol: 'MINDACORP.NS', name: 'Minda Corporation', sector: 'Auto' },
  { symbol: 'ZFCVINDIA.NS', name: 'ZF Commercial Vehicle', sector: 'Auto' },
  { symbol: 'SANDHAR.NS', name: 'Sandhar Technologies', sector: 'Auto' },
  { symbol: 'NRBBEARING.NS', name: 'NRB Bearings', sector: 'Auto' },
  { symbol: 'RAJRATAN.NS', name: 'Rajratan Global Wire', sector: 'Auto' },
  { symbol: 'PRICOLLTD.NS', name: 'Pricol Limited', sector: 'Auto' },
  { symbol: 'RANEHOLDIN.NS', name: 'Rane Holdings', sector: 'Auto' },
  { symbol: 'RANEENGINE.NS', name: 'Rane Engine Valve', sector: 'Auto' },
  { symbol: 'TVSSRICHAK.NS', name: 'TVS Srichakra', sector: 'Auto' },
  { symbol: 'AUTOAXLES.NS', name: 'Automotive Axles', sector: 'Auto' },
  { symbol: 'BANCOINDIA.NS', name: 'Banco Products India', sector: 'Auto' },
  { symbol: 'LUMAXIND.NS', name: 'Lumax Industries', sector: 'Auto' },
  { symbol: 'PRECAM.NS', name: 'Precision Camshafts', sector: 'Auto' },
  { symbol: 'RACL.NS', name: 'RACL Geartech', sector: 'Auto' },
  { symbol: 'FIEM.NS', name: 'Fiem Industries', sector: 'Auto' },
  { symbol: 'VSTTILLERS.NS', name: 'VST Tillers Tractors', sector: 'Auto' },
  { symbol: 'MAHINDCIE.NS', name: 'Mahindra CIE Automotive', sector: 'Auto' },

  // ========================================
  // === METALS ===
  // ========================================
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel', sector: 'Metals' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', sector: 'Metals' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'VEDL.NS', name: 'Vedanta Limited', sector: 'Metals' },
  { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel and Power', sector: 'Metals' },
  { symbol: 'SAIL.NS', name: 'Steel Authority of India', sector: 'Metals' },
  { symbol: 'NMDC.NS', name: 'NMDC Limited', sector: 'Metals' },
  { symbol: 'NATIONALUM.NS', name: 'National Aluminium Company', sector: 'Metals' },
  { symbol: 'HINDCOPPER.NS', name: 'Hindustan Copper', sector: 'Metals' },
  { symbol: 'HINDZINC.NS', name: 'Hindustan Zinc', sector: 'Metals' },
  { symbol: 'APLAPOLLO.NS', name: 'APL Apollo Tubes', sector: 'Metals' },
  { symbol: 'RATNAMANI.NS', name: 'Ratnamani Metals and Tubes', sector: 'Metals' },
  { symbol: 'WELCORP.NS', name: 'Welspun Corp', sector: 'Metals' },
  { symbol: 'SHYAMMETL.NS', name: 'Shyam Metalics and Energy', sector: 'Metals' },
  { symbol: 'TINPLATE.NS', name: 'Tinplate Company of India', sector: 'Metals' },
  { symbol: 'GRAVITA.NS', name: 'Gravita India', sector: 'Metals' },
  { symbol: 'RAIN.NS', name: 'Rain Industries', sector: 'Metals' },
  { symbol: 'GPIL.NS', name: 'Godawari Power and Ispat', sector: 'Metals' },
  { symbol: 'JSL.NS', name: 'Jindal Stainless', sector: 'Metals' },
  { symbol: 'JINDALSAW.NS', name: 'Jindal Saw', sector: 'Metals' },
  { symbol: 'TATAMETALI.NS', name: 'Tata Metaliks', sector: 'Metals' },
  { symbol: 'GALLANTT.NS', name: 'Gallantt Ispat', sector: 'Metals' },
  { symbol: 'PRAKASH.NS', name: 'Prakash Industries', sector: 'Metals' },
  { symbol: 'ELECTCAST.NS', name: 'Electrosteel Castings', sector: 'Metals' },
  { symbol: 'IFGLEXPOR.NS', name: 'IFGL Refractories', sector: 'Metals' },
  { symbol: 'IMFA.NS', name: 'Indian Metals and Ferro Alloys', sector: 'Metals' },
  { symbol: 'MAITHANALL.NS', name: 'Maithan Alloys', sector: 'Metals' },
  { symbol: 'SARDAEN.NS', name: 'Sarda Energy and Minerals', sector: 'Metals' },
  { symbol: 'JAIBALAJI.NS', name: 'Jai Balaji Industries', sector: 'Metals' },
  { symbol: 'MUKANDLTD.NS', name: 'Mukand Limited', sector: 'Metals' },
  { symbol: 'ORIENTREF.NS', name: 'Orient Refractories', sector: 'Metals' },
  { symbol: 'MANINDS.NS', name: 'Man Industries India', sector: 'Metals' },
  { symbol: 'JTLIND.NS', name: 'JTL Industries', sector: 'Metals' },
  { symbol: 'AGARIND.NS', name: 'Agarwal Industrial Corporation', sector: 'Metals' },

  // ========================================
  // === MINING ===
  // ========================================
  { symbol: 'COALINDIA.NS', name: 'Coal India', sector: 'Mining' },
  { symbol: 'MOIL.NS', name: 'MOIL Limited', sector: 'Mining' },
  { symbol: 'KIOCL.NS', name: 'KIOCL Limited', sector: 'Mining' },
  { symbol: 'GMDCLTD.NS', name: 'Gujarat Mineral Development', sector: 'Mining' },
  { symbol: 'ASHAPURMIN.NS', name: 'Ashapura Minechem', sector: 'Mining' },

  // ========================================
  // === CEMENT ===
  // ========================================
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', sector: 'Cement' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements', sector: 'Cement' },
  { symbol: 'ACC.NS', name: 'ACC Limited', sector: 'Cement' },
  { symbol: 'SHREECEM.NS', name: 'Shree Cement', sector: 'Cement' },
  { symbol: 'RAMCOCEM.NS', name: 'Ramco Cements', sector: 'Cement' },
  { symbol: 'JKCEMENT.NS', name: 'JK Cement', sector: 'Cement' },
  { symbol: 'DALMIACBHRT.NS', name: 'Dalmia Bharat', sector: 'Cement' },
  { symbol: 'BIRLACORPN.NS', name: 'Birla Corporation', sector: 'Cement' },
  { symbol: 'JKLAKSHMI.NS', name: 'JK Lakshmi Cement', sector: 'Cement' },
  { symbol: 'PRISMJOINS.NS', name: 'Prism Johnson', sector: 'Cement' },
  { symbol: 'HEIDELBERG.NS', name: 'HeidelbergCement India', sector: 'Cement' },
  { symbol: 'STARCEMENT.NS', name: 'Star Cement', sector: 'Cement' },
  { symbol: 'ORIENTCEM.NS', name: 'Orient Cement', sector: 'Cement' },
  { symbol: 'SAGCEM.NS', name: 'Sagar Cements', sector: 'Cement' },
  { symbol: 'INDIACEM.NS', name: 'India Cements', sector: 'Cement' },
  { symbol: 'NUVOCO.NS', name: 'Nuvoco Vistas Corporation', sector: 'Cement' },
  { symbol: 'KCP.NS', name: 'KCP Limited', sector: 'Cement' },
  { symbol: 'KESORAMIND.NS', name: 'Kesoram Industries', sector: 'Cement' },
  { symbol: 'SANGHIIND.NS', name: 'Sanghi Industries', sector: 'Cement' },
  { symbol: 'ANDHRACEMT.NS', name: 'Andhra Cements', sector: 'Cement' },

  // ========================================
  // === BUILDING MATERIALS ===
  // ========================================
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics', sector: 'Building Materials' },
  { symbol: 'SOMANY.NS', name: 'Somany Ceramics', sector: 'Building Materials' },
  { symbol: 'CERA.NS', name: 'Cera Sanitaryware', sector: 'Building Materials' },
  { symbol: 'CENTURYPLY.NS', name: 'Century Plyboards', sector: 'Building Materials' },
  { symbol: 'GREENPLY.NS', name: 'Greenply Industries', sector: 'Building Materials' },
  { symbol: 'ASTRAL.NS', name: 'Astral Limited', sector: 'Building Materials' },
  { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries', sector: 'Building Materials' },
  { symbol: 'PRINCEPIPE.NS', name: 'Prince Pipes and Fittings', sector: 'Building Materials' },
  { symbol: 'FINOLEX.NS', name: 'Finolex Industries', sector: 'Building Materials' },
  { symbol: 'APOLLOPIPE.NS', name: 'Apollo Pipes', sector: 'Building Materials' },
  { symbol: 'HINDWARE.NS', name: 'Hindware Home Innovation', sector: 'Building Materials' },
  { symbol: 'HIL.NS', name: 'HIL Limited', sector: 'Building Materials' },
  { symbol: 'EVERESTIND.NS', name: 'Everest Industries', sector: 'Building Materials' },
  { symbol: 'ORIENTBELL.NS', name: 'Orient Bell', sector: 'Building Materials' },
  { symbol: 'SHANKARA.NS', name: 'Shankara Building Products', sector: 'Building Materials' },
  { symbol: 'VISAKAIND.NS', name: 'Visaka Industries', sector: 'Building Materials' },
  { symbol: 'POKARNA.NS', name: 'Pokarna Limited', sector: 'Building Materials' },
  { symbol: 'CARYSIL.NS', name: 'Carysil Limited', sector: 'Building Materials' },
  { symbol: 'GREENPANEL.NS', name: 'Greenpanel Industries', sector: 'Building Materials' },
  { symbol: 'ARCHIDPLY.NS', name: 'Archidply Industries', sector: 'Building Materials' },

  // ========================================
  // === CHEMICALS ===
  // ========================================
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries', sector: 'Chemicals' },
  { symbol: 'UPL.NS', name: 'UPL Limited', sector: 'Chemicals' },
  { symbol: 'SRF.NS', name: 'SRF Limited', sector: 'Chemicals' },
  { symbol: 'AARTI.NS', name: 'Aarti Industries', sector: 'Chemicals' },
  { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite', sector: 'Chemicals' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine International', sector: 'Chemicals' },
  { symbol: 'ATUL.NS', name: 'Atul Limited', sector: 'Chemicals' },
  { symbol: 'CLEAN.NS', name: 'Clean Science and Technology', sector: 'Chemicals' },
  { symbol: 'FINEORG.NS', name: 'Fine Organic Industries', sector: 'Chemicals' },
  { symbol: 'ALKYLAMINE.NS', name: 'Alkyl Amines Chemicals', sector: 'Chemicals' },
  { symbol: 'GALAXYSURF.NS', name: 'Galaxy Surfactants', sector: 'Chemicals' },
  { symbol: 'ROSSARI.NS', name: 'Rossari Biotech', sector: 'Chemicals' },
  { symbol: 'TATACHEM.NS', name: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'GNFC.NS', name: 'Gujarat Narmada Valley Fertilizers', sector: 'Chemicals' },
  { symbol: 'GSFC.NS', name: 'Gujarat State Fertilizers', sector: 'Chemicals' },
  { symbol: 'COROMANDEL.NS', name: 'Coromandel International', sector: 'Chemicals' },
  { symbol: 'PIIND.NS', name: 'PI Industries', sector: 'Chemicals' },
  { symbol: 'SUMICHEM.NS', name: 'Sumitomo Chemical India', sector: 'Chemicals' },
  { symbol: 'RALLIS.NS', name: 'Rallis India', sector: 'Chemicals' },
  { symbol: 'NOCIL.NS', name: 'NOCIL Limited', sector: 'Chemicals' },
  { symbol: 'FLUOROCHEM.NS', name: 'Gujarat Fluorochemicals', sector: 'Chemicals' },
  { symbol: 'VINATIORG.NS', name: 'Vinati Organics', sector: 'Chemicals' },
  { symbol: 'ANURAS.NS', name: 'Anupam Rasayan India', sector: 'Chemicals' },
  { symbol: 'AARTIDRUGS.NS', name: 'Aarti Drugs', sector: 'Chemicals' },
  { symbol: 'LXCHEM.NS', name: 'Laxmi Organic Industries', sector: 'Chemicals' },
  { symbol: 'NEOGEN.NS', name: 'Neogen Chemicals', sector: 'Chemicals' },
  { symbol: 'PCBL.NS', name: 'PCBL Limited', sector: 'Chemicals' },
  { symbol: 'BASF.NS', name: 'BASF India', sector: 'Chemicals' },
  { symbol: 'SUDARSCHEM.NS', name: 'Sudarshan Chemical Industries', sector: 'Chemicals' },
  { symbol: 'BALAMINES.NS', name: 'Balaji Amines', sector: 'Chemicals' },
  { symbol: 'HERANBA.NS', name: 'Heranba Industries', sector: 'Chemicals' },
  { symbol: 'DEEPAKFERT.NS', name: 'Deepak Fertilisers', sector: 'Chemicals' },
  { symbol: 'GUJALKALI.NS', name: 'Gujarat Alkalies and Chemicals', sector: 'Chemicals' },
  { symbol: 'DCMSHRIRAM.NS', name: 'DCM Shriram', sector: 'Chemicals' },
  { symbol: 'CHAMBLFERT.NS', name: 'Chambal Fertilisers', sector: 'Chemicals' },
  { symbol: 'RCF.NS', name: 'Rashtriya Chemicals and Fertilizers', sector: 'Chemicals' },
  { symbol: 'FACT.NS', name: 'Fertilisers and Chemicals Travancore', sector: 'Chemicals' },
  { symbol: 'JUBLINGREA.NS', name: 'Jubilant Ingrevia', sector: 'Chemicals' },
  { symbol: 'GHCL.NS', name: 'GHCL Limited', sector: 'Chemicals' },
  { symbol: 'AETHER.NS', name: 'Aether Industries', sector: 'Chemicals' },
  { symbol: 'LINDEINDIA.NS', name: 'Linde India', sector: 'Chemicals' },
  { symbol: 'FAIRCHEM.NS', name: 'Fairchem Organics', sector: 'Chemicals' },
  { symbol: 'APCOTEX.NS', name: 'Apcotex Industries', sector: 'Chemicals' },
  { symbol: 'HOCL.NS', name: 'Hindustan Organic Chemicals', sector: 'Chemicals' },
  { symbol: 'ORIENTAROM.NS', name: 'Oriental Aromatics', sector: 'Chemicals' },
  { symbol: 'TANFAC.NS', name: 'Tanfac Industries', sector: 'Chemicals' },
  { symbol: 'PHILIPCARB.NS', name: 'Phillips Carbon Black', sector: 'Chemicals' },
  { symbol: 'BHAGERIA.NS', name: 'Bhageria Industries', sector: 'Chemicals' },
  { symbol: 'CAMLINFINE.NS', name: 'Camlin Fine Sciences', sector: 'Chemicals' },
  { symbol: 'CHEMFAB.NS', name: 'Chemfab Alkalis', sector: 'Chemicals' },
  { symbol: 'EPIGRAL.NS', name: 'Epigral Limited', sector: 'Chemicals' },
  { symbol: 'PRIVISCL.NS', name: 'Privi Speciality Chemicals', sector: 'Chemicals' },
  { symbol: 'BEPL.NS', name: 'Bhansali Engineering Polymers', sector: 'Chemicals' },
  { symbol: 'INEOSSTYRO.NS', name: 'INEOS Styrolution India', sector: 'Chemicals' },
  { symbol: 'MOL.NS', name: 'Meghmani Organics', sector: 'Chemicals' },
  { symbol: 'HIKAL.NS', name: 'Hikal Limited', sector: 'Chemicals' },
  { symbol: 'MANGCHEFER.NS', name: 'Mangalore Chemicals', sector: 'Chemicals' },
  { symbol: 'CHEMPLASTS.NS', name: 'Chemplast Sanmar', sector: 'Chemicals' },
  { symbol: 'IGPL.NS', name: 'India Glycols', sector: 'Chemicals' },
  { symbol: 'AARTISURF.NS', name: 'Aarti Surfactants', sector: 'Chemicals' },

  // ========================================
  // === POWER ===
  // ========================================
  { symbol: 'NTPC.NS', name: 'NTPC Limited', sector: 'Power' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation', sector: 'Power' },
  { symbol: 'TATAPOWER.NS', name: 'Tata Power Company', sector: 'Power' },
  { symbol: 'ADANIPOWER.NS', name: 'Adani Power', sector: 'Power' },
  { symbol: 'JSWENERGY.NS', name: 'JSW Energy', sector: 'Power' },
  { symbol: 'TORNTPOWER.NS', name: 'Torrent Power', sector: 'Power' },
  { symbol: 'NHPC.NS', name: 'NHPC Limited', sector: 'Power' },
  { symbol: 'SJVN.NS', name: 'SJVN Limited', sector: 'Power' },
  { symbol: 'CESC.NS', name: 'CESC Limited', sector: 'Power' },
  { symbol: 'NLCINDIA.NS', name: 'NLC India', sector: 'Power' },
  { symbol: 'SUZLON.NS', name: 'Suzlon Energy', sector: 'Power' },
  { symbol: 'INOXWIND.NS', name: 'Inox Wind', sector: 'Power' },
  { symbol: 'RPOWER.NS', name: 'Reliance Power', sector: 'Power' },
  { symbol: 'JPPOWER.NS', name: 'Jaiprakash Power Ventures', sector: 'Power' },
  { symbol: 'KECINTL.NS', name: 'KEC International', sector: 'Power' },
  { symbol: 'KALPATPOWR.NS', name: 'Kalpataru Projects International', sector: 'Power' },
  { symbol: 'GIPCL.NS', name: 'Gujarat Industries Power', sector: 'Power' },
  { symbol: 'RELINFRA.NS', name: 'Reliance Infrastructure', sector: 'Power' },
  { symbol: 'IEX.NS', name: 'Indian Energy Exchange', sector: 'Power' },
  { symbol: 'POWERINDIA.NS', name: 'Hitachi Energy India', sector: 'Power' },
  { symbol: 'SWSOLAR.NS', name: 'Sterling and Wilson Renewable Energy', sector: 'Power' },
  { symbol: 'GENUSPOWER.NS', name: 'Genus Power Infrastructures', sector: 'Power' },
  { symbol: 'HBLPOWER.NS', name: 'HBL Power Systems', sector: 'Power' },
  { symbol: 'NBVENTURES.NS', name: 'Nava Bharat Ventures', sector: 'Power' },
  { symbol: 'TECHNOE.NS', name: 'Techno Electric', sector: 'Power' },
  { symbol: 'ADANIENSOL.NS', name: 'Adani Energy Solutions', sector: 'Power' },
  { symbol: 'BOROLTD.NS', name: 'Borosil Renewables', sector: 'Power' },

  // ========================================
  // === TELECOM ===
  // ========================================
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'IDEA.NS', name: 'Vodafone Idea', sector: 'Telecom' },
  { symbol: 'INDUSTOWER.NS', name: 'Indus Towers', sector: 'Telecom' },
  { symbol: 'TATACOMM.NS', name: 'Tata Communications', sector: 'Telecom' },
  { symbol: 'HFCL.NS', name: 'HFCL Limited', sector: 'Telecom' },
  { symbol: 'STLTECH.NS', name: 'Sterlite Technologies', sector: 'Telecom' },
  { symbol: 'RAILTEL.NS', name: 'RailTel Corporation of India', sector: 'Telecom' },
  { symbol: 'TEJAS.NS', name: 'Tejas Networks', sector: 'Telecom' },
  { symbol: 'ITI.NS', name: 'ITI Limited', sector: 'Telecom' },
  { symbol: 'NELCO.NS', name: 'Nelco Limited', sector: 'Telecom' },
  { symbol: 'TTML.NS', name: 'Tata Teleservices Maharashtra', sector: 'Telecom' },

  // ========================================
  // === MEDIA ===
  // ========================================
  { symbol: 'SUNTV.NS', name: 'Sun TV Network', sector: 'Media' },
  { symbol: 'ZEEL.NS', name: 'Zee Entertainment Enterprises', sector: 'Media' },
  { symbol: 'NETWORK18.NS', name: 'Network18 Media and Investments', sector: 'Media' },
  { symbol: 'TV18BRDCST.NS', name: 'TV18 Broadcast', sector: 'Media' },
  { symbol: 'NAZARA.NS', name: 'Nazara Technologies', sector: 'Media' },
  { symbol: 'SAREGAMA.NS', name: 'Saregama India', sector: 'Media' },
  { symbol: 'NDTV.NS', name: 'New Delhi Television', sector: 'Media' },
  { symbol: 'DISHTV.NS', name: 'Dish TV India', sector: 'Media' },
  { symbol: 'DBCORP.NS', name: 'DB Corp', sector: 'Media' },
  { symbol: 'JAGRAN.NS', name: 'Jagran Prakashan', sector: 'Media' },
  { symbol: 'HTMEDIA.NS', name: 'HT Media', sector: 'Media' },
  { symbol: 'NAVNETEDUL.NS', name: 'Navneet Education', sector: 'Media' },
  { symbol: 'PVRINOX.NS', name: 'PVR Inox', sector: 'Media' },
  { symbol: 'HATHWAY.NS', name: 'Hathway Cable and Datacom', sector: 'Media' },
  { symbol: 'HMVL.NS', name: 'Hindustan Media Ventures', sector: 'Media' },
  { symbol: 'GTPL.NS', name: 'GTPL Hathway', sector: 'Media' },
  { symbol: 'ENIL.NS', name: 'Entertainment Network India', sector: 'Media' },
  { symbol: 'DEN.NS', name: 'DEN Networks', sector: 'Media' },

  // ========================================
  // === INFRASTRUCTURE ===
  // ========================================
  { symbol: 'LT.NS', name: 'Larsen and Toubro', sector: 'Infrastructure' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', sector: 'Infrastructure' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports and SEZ', sector: 'Infrastructure' },
  { symbol: 'IRB.NS', name: 'IRB Infrastructure Developers', sector: 'Infrastructure' },
  { symbol: 'NCC.NS', name: 'NCC Limited', sector: 'Infrastructure' },
  { symbol: 'NBCC.NS', name: 'NBCC India', sector: 'Infrastructure' },
  { symbol: 'PNC.NS', name: 'PNC Infratech', sector: 'Infrastructure' },
  { symbol: 'KNRCON.NS', name: 'KNR Constructions', sector: 'Infrastructure' },
  { symbol: 'HCC.NS', name: 'Hindustan Construction Company', sector: 'Infrastructure' },
  { symbol: 'ENGINERSIN.NS', name: 'Engineers India', sector: 'Infrastructure' },
  { symbol: 'HGINFRA.NS', name: 'H G Infra Engineering', sector: 'Infrastructure' },
  { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam', sector: 'Infrastructure' },
  { symbol: 'RITES.NS', name: 'RITES Limited', sector: 'Infrastructure' },
  { symbol: 'IRCON.NS', name: 'Ircon International', sector: 'Infrastructure' },
  { symbol: 'TITAGARH.NS', name: 'Titagarh Rail Systems', sector: 'Infrastructure' },
  { symbol: 'JSWINFRA.NS', name: 'JSW Infrastructure', sector: 'Infrastructure' },
  { symbol: 'AHLUCONT.NS', name: 'Ahluwalia Contracts India', sector: 'Infrastructure' },
  { symbol: 'GPPL.NS', name: 'Gujarat Pipavav Port', sector: 'Infrastructure' },
  { symbol: 'WABAG.NS', name: 'VA Tech Wabag', sector: 'Infrastructure' },
  { symbol: 'PSP.NS', name: 'PSP Projects', sector: 'Infrastructure' },
  { symbol: 'MANINFRA.NS', name: 'Man Infraconstruction', sector: 'Infrastructure' },
  { symbol: 'DILIPBUILD.NS', name: 'Dilip Buildcon', sector: 'Infrastructure' },
  { symbol: 'ASHOKA.NS', name: 'Ashoka Buildcon', sector: 'Infrastructure' },
  { symbol: 'PATELENG.NS', name: 'Patel Engineering', sector: 'Infrastructure' },
  { symbol: 'GRINFRA.NS', name: 'GR Infraprojects', sector: 'Infrastructure' },
  { symbol: 'ITDCEM.NS', name: 'ITD Cementation India', sector: 'Infrastructure' },
  { symbol: 'WELENT.NS', name: 'Welspun Enterprises', sector: 'Infrastructure' },
  { symbol: 'BLKASHYAP.NS', name: 'BL Kashyap and Sons', sector: 'Infrastructure' },

  // ========================================
  // === REAL ESTATE ===
  // ========================================
  { symbol: 'DLF.NS', name: 'DLF Limited', sector: 'Real Estate' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties', sector: 'Real Estate' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty', sector: 'Real Estate' },
  { symbol: 'PHOENIXLTD.NS', name: 'Phoenix Mills', sector: 'Real Estate' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates Projects', sector: 'Real Estate' },
  { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises', sector: 'Real Estate' },
  { symbol: 'SOBHA.NS', name: 'Sobha Limited', sector: 'Real Estate' },
  { symbol: 'SUNTECK.NS', name: 'Sunteck Realty', sector: 'Real Estate' },
  { symbol: 'MAHLIFE.NS', name: 'Mahindra Lifespace Developers', sector: 'Real Estate' },
  { symbol: 'LODHA.NS', name: 'Macrotech Developers (Lodha)', sector: 'Real Estate' },
  { symbol: 'KOLTEPATIL.NS', name: 'Kolte-Patil Developers', sector: 'Real Estate' },
  { symbol: 'PURVA.NS', name: 'Puravankara Limited', sector: 'Real Estate' },
  { symbol: 'KEYSTONE.NS', name: 'Keystone Realtors', sector: 'Real Estate' },
  { symbol: 'SIGNATURE.NS', name: 'Signatureglobal India', sector: 'Real Estate' },
  { symbol: 'ANANTRAJ.NS', name: 'Anant Raj', sector: 'Real Estate' },
  { symbol: 'NESCO.NS', name: 'Nesco Limited', sector: 'Real Estate' },
  { symbol: 'AJMERA.NS', name: 'Ajmera Realty and Infra', sector: 'Real Estate' },
  { symbol: 'ASHIANA.NS', name: 'Ashiana Housing', sector: 'Real Estate' },
  { symbol: 'GANESHHOUC.NS', name: 'Ganesh Housing Corporation', sector: 'Real Estate' },
  { symbol: 'MARATHON.NS', name: 'Marathon Nextgen Realty', sector: 'Real Estate' },

  // ========================================
  // === CONSUMER DURABLES ===
  // ========================================
  { symbol: 'TITAN.NS', name: 'Titan Company', sector: 'Consumer Durables' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', sector: 'Consumer Durables' },
  { symbol: 'HAVELLS.NS', name: 'Havells India', sector: 'Consumer Durables' },
  { symbol: 'VOLTAS.NS', name: 'Voltas Limited', sector: 'Consumer Durables' },
  { symbol: 'BLUESTARLT.NS', name: 'Blue Star', sector: 'Consumer Durables' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Greaves Consumer', sector: 'Consumer Durables' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies', sector: 'Consumer Durables' },
  { symbol: 'KAYNES.NS', name: 'Kaynes Technology India', sector: 'Consumer Durables' },
  { symbol: 'AMBER.NS', name: 'Amber Enterprises India', sector: 'Consumer Durables' },
  { symbol: 'VGUARD.NS', name: 'V-Guard Industries', sector: 'Consumer Durables' },
  { symbol: 'BATAINDIA.NS', name: 'Bata India', sector: 'Consumer Durables' },
  { symbol: 'RELAXO.NS', name: 'Relaxo Footwears', sector: 'Consumer Durables' },
  { symbol: 'KALYANJEWL.NS', name: 'Kalyan Jewellers India', sector: 'Consumer Durables' },
  { symbol: 'ORIENTELEC.NS', name: 'Orient Electric', sector: 'Consumer Durables' },
  { symbol: 'IFBIND.NS', name: 'IFB Industries', sector: 'Consumer Durables' },
  { symbol: 'TTKPRESTIG.NS', name: 'TTK Prestige', sector: 'Consumer Durables' },
  { symbol: 'WHIRLPOOL.NS', name: 'Whirlpool of India', sector: 'Consumer Durables' },
  { symbol: 'STOVEKRAFT.NS', name: 'Stove Kraft', sector: 'Consumer Durables' },
  { symbol: 'SYMPHONY.NS', name: 'Symphony Limited', sector: 'Consumer Durables' },
  { symbol: 'CELLO.NS', name: 'Cello World', sector: 'Consumer Durables' },
  { symbol: 'NILKAMAL.NS', name: 'Nilkamal Limited', sector: 'Consumer Durables' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints India', sector: 'Consumer Durables' },
  { symbol: 'KANSAINER.NS', name: 'Kansai Nerolac Paints', sector: 'Consumer Durables' },
  { symbol: 'AKZOINDIA.NS', name: 'Akzo Nobel India', sector: 'Consumer Durables' },
  { symbol: 'INDIGOPNTS.NS', name: 'Indigo Paints', sector: 'Consumer Durables' },
  { symbol: 'SENCO.NS', name: 'Senco Gold', sector: 'Consumer Durables' },
  { symbol: 'BOROSIL.NS', name: 'Borosil Limited', sector: 'Consumer Durables' },
  { symbol: 'LAOPALA.NS', name: 'La Opala RG', sector: 'Consumer Durables' },
  { symbol: 'KDDL.NS', name: 'KDDL Limited', sector: 'Consumer Durables' },
  { symbol: 'PGEL.NS', name: 'PG Electroplast', sector: 'Consumer Durables' },
  { symbol: 'SAFARI.NS', name: 'Safari Industries', sector: 'Consumer Durables' },
  { symbol: 'VIPIND.NS', name: 'VIP Industries', sector: 'Consumer Durables' },
  { symbol: 'VAIBHAVGBL.NS', name: 'Vaibhav Global', sector: 'Consumer Durables' },
  { symbol: 'SURYAROSNI.NS', name: 'Surya Roshni', sector: 'Consumer Durables' },
  { symbol: 'THANGAMAYL.NS', name: 'Thangamayil Jewellery', sector: 'Consumer Durables' },
  { symbol: 'RAJESHEXPO.NS', name: 'Rajesh Exports', sector: 'Consumer Durables' },
  { symbol: 'JCHAC.NS', name: 'Johnson Controls Hitachi AC', sector: 'Consumer Durables' },
  { symbol: 'BUTTERFLY.NS', name: 'Butterfly Gandhimathi Appliances', sector: 'Consumer Durables' },
  { symbol: 'TTKHLTCARE.NS', name: 'TTK Healthcare', sector: 'Consumer Durables' },

  // ========================================
  // === CAPITAL GOODS ===
  // ========================================
  { symbol: 'ABB.NS', name: 'ABB India', sector: 'Capital Goods' },
  { symbol: 'SIEMENS.NS', name: 'Siemens India', sector: 'Capital Goods' },
  { symbol: 'HONAUT.NS', name: 'Honeywell Automation India', sector: 'Capital Goods' },
  { symbol: 'BHEL.NS', name: 'Bharat Heavy Electricals', sector: 'Capital Goods' },
  { symbol: 'CUMMINSIND.NS', name: 'Cummins India', sector: 'Capital Goods' },
  { symbol: 'AIAENG.NS', name: 'AIA Engineering', sector: 'Capital Goods' },
  { symbol: 'ELGIEQUIP.NS', name: 'Elgi Equipments', sector: 'Capital Goods' },
  { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton', sector: 'Capital Goods' },
  { symbol: 'CGPOWER.NS', name: 'CG Power and Industrial Solutions', sector: 'Capital Goods' },
  { symbol: 'TRIVENI.NS', name: 'Triveni Turbine', sector: 'Capital Goods' },
  { symbol: 'KENNAMET.NS', name: 'Kennametal India', sector: 'Capital Goods' },
  { symbol: 'TIMKEN.NS', name: 'Timken India', sector: 'Capital Goods' },
  { symbol: 'SKFINDIA.NS', name: 'SKF India', sector: 'Capital Goods' },
  { symbol: 'PRAJ.NS', name: 'Praj Industries', sector: 'Capital Goods' },
  { symbol: 'ELECON.NS', name: 'Elecon Engineering', sector: 'Capital Goods' },
  { symbol: 'KIRLOSENG.NS', name: 'Kirloskar Oil Engines', sector: 'Capital Goods' },
  { symbol: 'KIRLOSBROS.NS', name: 'Kirloskar Brothers', sector: 'Capital Goods' },
  { symbol: 'THERMAX.NS', name: 'Thermax Limited', sector: 'Capital Goods' },
  { symbol: 'BEML.NS', name: 'BEML Limited', sector: 'Capital Goods' },
  { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal', sector: 'Capital Goods' },
  { symbol: 'VOLTAMP.NS', name: 'Voltamp Transformers', sector: 'Capital Goods' },
  { symbol: 'TDPOWERSYS.NS', name: 'TD Power Systems', sector: 'Capital Goods' },
  { symbol: 'DYNAMATECH.NS', name: 'Dynamatic Technologies', sector: 'Capital Goods' },
  { symbol: 'INOXINDIA.NS', name: 'INOX India', sector: 'Capital Goods' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India', sector: 'Capital Goods' },
  { symbol: 'KEI.NS', name: 'KEI Industries', sector: 'Capital Goods' },
  { symbol: 'FINCABLES.NS', name: 'Finolex Cables', sector: 'Capital Goods' },
  { symbol: 'HEG.NS', name: 'HEG Limited', sector: 'Capital Goods' },
  { symbol: 'GRAPHITE.NS', name: 'Graphite India', sector: 'Capital Goods' },
  { symbol: 'PENIND.NS', name: 'Pennar Industries', sector: 'Capital Goods' },
  { symbol: 'ISGEC.NS', name: 'ISGEC Heavy Engineering', sector: 'Capital Goods' },
  { symbol: 'GMMPFAUD.NS', name: 'GMM Pfaudler', sector: 'Capital Goods' },
  { symbol: 'JASH.NS', name: 'Jash Engineering', sector: 'Capital Goods' },
  { symbol: 'ESABINDIA.NS', name: 'ESAB India', sector: 'Capital Goods' },
  { symbol: 'GEPIL.NS', name: 'GE Power India', sector: 'Capital Goods' },
  { symbol: 'ACE.NS', name: 'Action Construction Equipment', sector: 'Capital Goods' },
  { symbol: 'APARINDS.NS', name: 'Apar Industries', sector: 'Capital Goods' },
  { symbol: 'TEGA.NS', name: 'Tega Industries', sector: 'Capital Goods' },
  { symbol: 'JYOTI.NS', name: 'Jyoti CNC Automation', sector: 'Capital Goods' },
  { symbol: 'LAXMIMACH.NS', name: 'Lakshmi Machine Works', sector: 'Capital Goods' },
  { symbol: 'WPIL.NS', name: 'WPIL Limited', sector: 'Capital Goods' },
  { symbol: 'CONTROLPR.NS', name: 'Control Print', sector: 'Capital Goods' },
  { symbol: 'SBCL.NS', name: 'Shivalik Bimetal Controls', sector: 'Capital Goods' },

  // ========================================
  // === DEFENCE ===
  // ========================================
  { symbol: 'HAL.NS', name: 'Hindustan Aeronautics', sector: 'Defence' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics', sector: 'Defence' },
  { symbol: 'BDL.NS', name: 'Bharat Dynamics', sector: 'Defence' },
  { symbol: 'MAZAGON.NS', name: 'Mazagon Dock Shipbuilders', sector: 'Defence' },
  { symbol: 'COCHINSHIP.NS', name: 'Cochin Shipyard', sector: 'Defence' },
  { symbol: 'GRSE.NS', name: 'Garden Reach Shipbuilders', sector: 'Defence' },
  { symbol: 'SOLARINDS.NS', name: 'Solar Industries India', sector: 'Defence' },
  { symbol: 'ZENTEC.NS', name: 'Zen Technologies', sector: 'Defence' },
  { symbol: 'ASTRA.NS', name: 'Astra Microwave Products', sector: 'Defence' },
  { symbol: 'MIDHANI.NS', name: 'Mishra Dhatu Nigam', sector: 'Defence' },
  { symbol: 'IDEAFORGE.NS', name: 'ideaForge Technology', sector: 'Defence' },
  { symbol: 'PARAS.NS', name: 'Paras Defence and Space Technologies', sector: 'Defence' },
  { symbol: 'MTARTECH.NS', name: 'MTAR Technologies', sector: 'Defence' },

  // ========================================
  // === TEXTILES ===
  // ========================================
  { symbol: 'PAGEIND.NS', name: 'Page Industries', sector: 'Textiles' },
  { symbol: 'ABFRL.NS', name: 'Aditya Birla Fashion and Retail', sector: 'Textiles' },
  { symbol: 'ARVIND.NS', name: 'Arvind Limited', sector: 'Textiles' },
  { symbol: 'RAYMOND.NS', name: 'Raymond Limited', sector: 'Textiles' },
  { symbol: 'KPRMILL.NS', name: 'KPR Mill', sector: 'Textiles' },
  { symbol: 'GOKEX.NS', name: 'Gokaldas Exports', sector: 'Textiles' },
  { symbol: 'KITEX.NS', name: 'Kitex Garments', sector: 'Textiles' },
  { symbol: 'TRIDENT.NS', name: 'Trident Limited', sector: 'Textiles' },
  { symbol: 'VARDHMAN.NS', name: 'Vardhman Textiles', sector: 'Textiles' },
  { symbol: 'HIMATSEIDE.NS', name: 'Himatsingka Seide', sector: 'Textiles' },
  { symbol: 'SPAL.NS', name: 'S P Apparels', sector: 'Textiles' },
  { symbol: 'WELSPUNLIV.NS', name: 'Welspun Living', sector: 'Textiles' },
  { symbol: 'CENTURYTEX.NS', name: 'Century Textiles and Industries', sector: 'Textiles' },
  { symbol: 'DOLLAR.NS', name: 'Dollar Industries', sector: 'Textiles' },
  { symbol: 'LUXIND.NS', name: 'Lux Industries', sector: 'Textiles' },
  { symbol: 'GARFIBRES.NS', name: 'Garware Technical Fibres', sector: 'Textiles' },
  { symbol: 'SANGAMIND.NS', name: 'Sangam India', sector: 'Textiles' },
  { symbol: 'ALOKINDS.NS', name: 'Alok Industries', sector: 'Textiles' },
  { symbol: 'ARVINDFASN.NS', name: 'Arvind Fashions', sector: 'Textiles' },
  { symbol: 'MONTECARLO.NS', name: 'Monte Carlo Fashions', sector: 'Textiles' },
  { symbol: 'PDSL.NS', name: 'PDS Limited', sector: 'Textiles' },
  { symbol: 'MALLCOM.NS', name: 'Mallcom India', sector: 'Textiles' },
  { symbol: 'MAYURUNIQ.NS', name: 'Mayur Uniquoters', sector: 'Textiles' },
  { symbol: 'ZODIACLOTH.NS', name: 'Zodiac Clothing', sector: 'Textiles' },
  { symbol: 'TCNSBRANDS.NS', name: 'TCNS Clothing', sector: 'Textiles' },

  // ========================================
  // === RETAIL ===
  // ========================================
  { symbol: 'DMART.NS', name: 'Avenue Supermarts (DMart)', sector: 'Retail' },
  { symbol: 'TRENT.NS', name: 'Trent Limited', sector: 'Retail' },
  { symbol: 'SHOPERSTOP.NS', name: 'Shoppers Stop', sector: 'Retail' },
  { symbol: 'VMART.NS', name: 'V-Mart Retail', sector: 'Retail' },
  { symbol: 'METROBRAND.NS', name: 'Metro Brands', sector: 'Retail' },
  { symbol: 'CAMPUS.NS', name: 'Campus Activewear', sector: 'Retail' },
  { symbol: 'ETHOS.NS', name: 'Ethos Limited', sector: 'Retail' },
  { symbol: 'MANYAVAR.NS', name: 'Vedant Fashions (Manyavar)', sector: 'Retail' },
  { symbol: 'GOCOLORS.NS', name: 'Go Fashion India', sector: 'Retail' },
  { symbol: 'KALAMANDIR.NS', name: 'Sai Silks Kalamandir', sector: 'Retail' },
  { symbol: 'CANTABIL.NS', name: 'Cantabil Retail India', sector: 'Retail' },

  // ========================================
  // === AVIATION ===
  // ========================================
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation (IndiGo)', sector: 'Aviation' },
  { symbol: 'SPICEJET.NS', name: 'SpiceJet', sector: 'Aviation' },

  // ========================================
  // === TRAVEL ===
  // ========================================
  { symbol: 'IRCTC.NS', name: 'Indian Railway Catering and Tourism', sector: 'Travel' },
  { symbol: 'EASEMYTRIP.NS', name: 'Easy Trip Planners', sector: 'Travel' },
  { symbol: 'THOMASCOOK.NS', name: 'Thomas Cook India', sector: 'Travel' },
  { symbol: 'YATRA.NS', name: 'Yatra Online', sector: 'Travel' },
  { symbol: 'DREAMFOLK.NS', name: 'Dreamfolks Services', sector: 'Travel' },

  // ========================================
  // === HOTELS ===
  // ========================================
  { symbol: 'INDHOTEL.NS', name: 'Indian Hotels Company (Taj)', sector: 'Hotels' },
  { symbol: 'LEMONTRE.NS', name: 'Lemon Tree Hotels', sector: 'Hotels' },
  { symbol: 'EIHOTEL.NS', name: 'EIH Limited (Oberoi Hotels)', sector: 'Hotels' },
  { symbol: 'CHALET.NS', name: 'Chalet Hotels', sector: 'Hotels' },
  { symbol: 'JUNIPER.NS', name: 'Juniper Hotels', sector: 'Hotels' },
  { symbol: 'TAJGVK.NS', name: 'TajGVK Hotels and Resorts', sector: 'Hotels' },
  { symbol: 'BARBEQUE.NS', name: 'Barbeque Nation Hospitality', sector: 'Hotels' },
  { symbol: 'MHRIL.NS', name: 'Mahindra Holidays', sector: 'Hotels' },
  { symbol: 'ORIENTHOT.NS', name: 'Oriental Hotels', sector: 'Hotels' },
  { symbol: 'DELTACORP.NS', name: 'Delta Corp', sector: 'Hotels' },

  // ========================================
  // === LOGISTICS ===
  // ========================================
  { symbol: 'CONCOR.NS', name: 'Container Corporation of India', sector: 'Logistics' },
  { symbol: 'DELHIVERY.NS', name: 'Delhivery Limited', sector: 'Logistics' },
  { symbol: 'BLUEDART.NS', name: 'Blue Dart Express', sector: 'Logistics' },
  { symbol: 'MAHLOG.NS', name: 'Mahindra Logistics', sector: 'Logistics' },
  { symbol: 'ALLCARGO.NS', name: 'Allcargo Logistics', sector: 'Logistics' },
  { symbol: 'TCI.NS', name: 'Transport Corporation of India', sector: 'Logistics' },
  { symbol: 'GATEWAY.NS', name: 'Gateway Distriparks', sector: 'Logistics' },
  { symbol: 'VRL.NS', name: 'VRL Logistics', sector: 'Logistics' },
  { symbol: 'TCIEXP.NS', name: 'TCI Express', sector: 'Logistics' },

  // ========================================
  // === SHIPPING ===
  // ========================================
  { symbol: 'GESHIP.NS', name: 'Great Eastern Shipping', sector: 'Shipping' },
  { symbol: 'SCI.NS', name: 'Shipping Corporation of India', sector: 'Shipping' },

  // ========================================
  // === AGRICULTURE ===
  // ========================================
  { symbol: 'DHANUKA.NS', name: 'Dhanuka Agritech', sector: 'Agriculture' },
  { symbol: 'BAYERCROP.NS', name: 'Bayer CropScience', sector: 'Agriculture' },
  { symbol: 'KAVERI.NS', name: 'Kaveri Seed Company', sector: 'Agriculture' },
  { symbol: 'BALRAMCHIN.NS', name: 'Balrampur Chini Mills', sector: 'Agriculture' },
  { symbol: 'RENUKA.NS', name: 'Shree Renuka Sugars', sector: 'Agriculture' },
  { symbol: 'DWARIKESH.NS', name: 'Dwarikesh Sugar Industries', sector: 'Agriculture' },
  { symbol: 'AVANTIFEED.NS', name: 'Avanti Feeds', sector: 'Agriculture' },
  { symbol: 'GODREJAGRO.NS', name: 'Godrej Agrovet', sector: 'Agriculture' },
  { symbol: 'SHARDACROP.NS', name: 'Sharda Cropchem', sector: 'Agriculture' },
  { symbol: 'BAJAJHIND.NS', name: 'Bajaj Hindusthan Sugar', sector: 'Agriculture' },
  { symbol: 'DALMIASUG.NS', name: 'Dalmia Bharat Sugar', sector: 'Agriculture' },
  { symbol: 'DHAMPURSUG.NS', name: 'Dhampur Sugar Mills', sector: 'Agriculture' },
  { symbol: 'WATERBASE.NS', name: 'Waterbase Limited', sector: 'Agriculture' },
  { symbol: 'ASTEC.NS', name: 'Astec LifeSciences', sector: 'Agriculture' },
  { symbol: 'INSECTICID.NS', name: 'Insecticides India', sector: 'Agriculture' },
  { symbol: 'JISLJALEQS.NS', name: 'Jain Irrigation Systems', sector: 'Agriculture' },
  { symbol: 'BANARISUG.NS', name: 'Bannari Amman Sugars', sector: 'Agriculture' },
  { symbol: 'ANDHRSUGAR.NS', name: 'Andhra Sugars', sector: 'Agriculture' },
  { symbol: 'EIDPARRY.NS', name: 'EID Parry', sector: 'Agriculture' },
  { symbol: 'TRIVENIENG.NS', name: 'Triveni Engineering', sector: 'Agriculture' },

  // ========================================
  // === PAPER ===
  // ========================================
  { symbol: 'JKPAPER.NS', name: 'JK Paper', sector: 'Paper' },
  { symbol: 'TNPL.NS', name: 'Tamil Nadu Newsprint', sector: 'Paper' },
  { symbol: 'ANDHRAPAP.NS', name: 'Andhra Paper', sector: 'Paper' },
  { symbol: 'WSTCSTPAPR.NS', name: 'West Coast Paper Mills', sector: 'Paper' },
  { symbol: 'ORIENTPPR.NS', name: 'Orient Paper', sector: 'Paper' },

  // ========================================
  // === PACKAGING ===
  // ========================================
  { symbol: 'HUHTAMAKI.NS', name: 'Huhtamaki India', sector: 'Packaging' },
  { symbol: 'EPL.NS', name: 'EPL Limited', sector: 'Packaging' },
  { symbol: 'UFLEX.NS', name: 'Uflex Limited', sector: 'Packaging' },
  { symbol: 'COSMOFIRST.NS', name: 'Cosmo First', sector: 'Packaging' },

  // ========================================
  // === SERVICES ===
  // ========================================
  { symbol: 'SIS.NS', name: 'SIS Limited', sector: 'Services' },
  { symbol: 'TEAMLEASE.NS', name: 'TeamLease Services', sector: 'Services' },

  // ========================================
  // === TRADING ===
  // ========================================
  { symbol: 'MMTC.NS', name: 'MMTC Limited', sector: 'Trading' },
  { symbol: 'MSTCLTD.NS', name: 'MSTC Limited', sector: 'Trading' },

  // ========================================
  // === DIVERSIFIED ===
  // ========================================
  { symbol: '3MINDIA.NS', name: '3M India', sector: 'Diversified' },
  { symbol: 'ZUARIIND.NS', name: 'Zuari Industries', sector: 'Diversified' },
  { symbol: 'ANDREWYU.NS', name: 'Andrew Yule and Company', sector: 'Diversified' },

  // ========================================
  // === ADDITIONAL NSE STOCKS ===
  // ========================================
  { symbol: 'ABIRLANUVO.NS', name: 'Aditya Birla Capital', sector: 'Financial Services' },
  { symbol: 'AGROPHOS.NS', name: 'Agro Phos India', sector: 'Chemicals' },
  { symbol: 'AHLEAST.NS', name: 'Asian Hotels East', sector: 'Hotels' },
  { symbol: 'ALANKIT.NS', name: 'Alankit', sector: 'Financial Services' },
  { symbol: 'APCL.NS', name: 'Authum Investment', sector: 'Financial Services' },
  { symbol: 'BCG.NS', name: 'Brightcom Group', sector: 'IT' },
  { symbol: 'DALBHARAT.NS', name: 'Dalmia Bharat', sector: 'Cement' },
  { symbol: 'DHANI.NS', name: 'Dhani Services', sector: 'Financial Services' },
  { symbol: 'ESSELPRO.NS', name: 'Essel Propack', sector: 'Packaging' },
  { symbol: 'HEMIPROP.NS', name: 'Hemisphere Properties', sector: 'Real Estate' },
  { symbol: 'MAHSEAMLES.NS', name: 'Maharashtra Seamless', sector: 'Metals' },
  { symbol: 'NSLNISP.NS', name: 'NMDC Steel', sector: 'Metals' },
  { symbol: 'ZUARI.NS', name: 'Zuari Agro Chemicals', sector: 'Chemicals' },
  { symbol: 'SUPPETRO.NS', name: 'Supreme Petrochem', sector: 'Energy' },
  { symbol: 'GANDPHARMA.NS', name: 'Gandhi Special Tubes', sector: 'Energy' },
  { symbol: 'SUBEXLTD.NS', name: 'Subex Limited', sector: 'IT' },
  { symbol: 'INFIBEAM.NS', name: 'Infibeam Avenues', sector: 'IT' },
  { symbol: 'OPTIEMUS.NS', name: 'Optiemus Infracom', sector: 'IT' },
  { symbol: 'PALREDTECH.NS', name: 'Palred Technologies', sector: 'IT' },
  { symbol: 'COMPUSOFT.NS', name: 'Compucom Software', sector: 'IT' },
  { symbol: 'OCCL.NS', name: 'Oriental Carbon and Chemicals', sector: 'IT' },
  { symbol: 'GTLINFRA.NS', name: 'GTL Infrastructure', sector: 'IT' },
  { symbol: 'ZENITHSTL.NS', name: 'Zenith Steel Pipes', sector: 'IT' },
  { symbol: 'NAINITALBNK.NS', name: 'Nainital Bank', sector: 'Banking' },
  { symbol: 'ARIHANTCAP.NS', name: 'Arihant Capital Markets', sector: 'Financial Services' },
  { symbol: 'MASFIN.NS', name: 'MAS Financial Services', sector: 'Financial Services' },
  { symbol: 'L&TFH.NS', name: 'L&T Finance', sector: 'Financial Services' },
  { symbol: 'IIFLWAM.NS', name: 'IIFL Wealth Management', sector: 'Financial Services' },
  { symbol: 'EQUITAS.NS', name: 'Equitas Holdings', sector: 'Financial Services' },
  { symbol: 'CHOLAHLDNG.NS', name: 'Cholamandalam Financial Holdings', sector: 'Financial Services' },
  { symbol: 'IDFC.NS', name: 'IDFC Limited', sector: 'Financial Services' },
  { symbol: 'JSWHL.NS', name: 'JSW Holdings', sector: 'Financial Services' },
  { symbol: 'VENKEYS.NS', name: 'Venky India', sector: 'FMCG' },
  { symbol: 'TATACOFFEE.NS', name: 'Tata Coffee', sector: 'FMCG' },
  { symbol: 'AARTIPHARM.NS', name: 'Aarti Pharmalab', sector: 'Pharma' },
  { symbol: 'WHEELS.NS', name: 'Wheels India', sector: 'Auto' },
  { symbol: 'MISHRA.NS', name: 'Mishra Dhatu Nigam', sector: 'Metals' },
  { symbol: 'MADRASFER.NS', name: 'Madras Fertilizers', sector: 'Chemicals' },
  { symbol: 'SRHHYPOLTD.NS', name: 'Sree Rayalaseema Hi-Strength Hypo', sector: 'Chemicals' },
  { symbol: 'YASHCHEM.NS', name: 'Yash Chemex', sector: 'Chemicals' },
  { symbol: 'DMCC.NS', name: 'DMCC Speciality Chemicals', sector: 'Chemicals' },
  { symbol: 'DHARAMSI.NS', name: 'Dharamsi Morarji Chemical', sector: 'Chemicals' },
  { symbol: 'ASAHISONG.NS', name: 'Asahi Songwon Colors', sector: 'Chemicals' },
  { symbol: 'ADANITRANS.NS', name: 'Adani Transmission', sector: 'Power' },
  { symbol: 'DPSCLTD.NS', name: 'DPSC Limited', sector: 'Power' },
  { symbol: 'BFUTILITIE.NS', name: 'BF Utilities', sector: 'Power' },
  { symbol: 'DONEAR.NS', name: 'Donear Industries', sector: 'Textiles' },
  { symbol: 'AYMSYNTEX.NS', name: 'AYM Syntex', sector: 'Textiles' },
  { symbol: 'TIRUPATIND.NS', name: 'Tirupati Industries', sector: 'Textiles' },
  { symbol: 'TVTODAY.NS', name: 'TV Today Network', sector: 'Media' },
  { symbol: 'EROSMEDIA.NS', name: 'Eros STX Global', sector: 'Media' },
  { symbol: 'PHANTOMFX.NS', name: 'Phantom Digital Effects', sector: 'Media' },
  { symbol: 'SADBHAV.NS', name: 'Sadbhav Engineering', sector: 'Infrastructure' },
  { symbol: 'CAPACITE.NS', name: 'Capacite Infraprojects', sector: 'Infrastructure' },
  { symbol: 'JMCPROJ.NS', name: 'JMC Projects India', sector: 'Infrastructure' },
  { symbol: 'NATH.NS', name: 'Nath Bio-Genes India', sector: 'Agriculture' },
  { symbol: 'KOTARISUG.NS', name: 'Kothari Sugars', sector: 'Agriculture' },
  { symbol: 'CLEDUCATE.NS', name: 'CL Educate', sector: 'Services' },
  { symbol: 'SHALPAINTS.NS', name: 'Shalimar Paints', sector: 'Paint' },
];

// Deduplicate by symbol (first occurrence wins)
const seen = new Set();
const UNIQUE_SYMBOLS = NSE_SYMBOLS.filter(s => {
  if (seen.has(s.symbol)) return false;
  seen.add(s.symbol);
  return true;
});

module.exports = UNIQUE_SYMBOLS;
